# Site
name: "GILog"
description: "Back-end Developer"
favicon: "assets/images/logo/favicon2.ico"
baseurl: ""
email: "seob31@gmail.com"
photo: assets/images/me/me.jpg
utterances:
  repo: "seob31/blog-reply"
  issue-term: "pathname"
  theme: "github-light"
# logo: 'assets/images/logo/gilog.png'

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# blog topics
topics:
  architecture:
    name: Architecture
    img: assets/images/topic/architecture.png
    url: architecture
  backend:
    name: Back-end
    img: assets/images/topic/backend.png
    url: backend
  frontend:
    name: Front-end
    img: assets/images/topic/frontend.png
    url: frontend
  cloud:
    name: Cloud&Container
    img: assets/images/topic/cloud.png
    url: cloud
  devops:
    name: DevOps
    img: assets/images/topic/devOps.png
    url: devops
  db:
    name: DataBase
    img: assets/images/topic/db.png
    url: db
  os:
    name: OS
    img: assets/images/topic/os.png
    url: os
  others:
    name: Others
    img: assets/images/topic/others.png
    url: others

include: ["_pages"]
permalink: /:title/

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts/en"
    values:
      layout: post
      permalink: 'en/posts/:title'
      language: en
  - scope:
      path: "_posts/ko"
    values:
      layout: post
      permalink: 'posts/:title'
      language: ko

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

    # all stroy
  - scope:
      path: "_stories/ko"
      type: stories
    values:
      layout: story
      permalink: 'stories/:title'
      language: ko
  - scope:
      path: "_stories/en"
      type: stories
    values:
      layout: story
      permalink: 'en/stories/:title'
      language: en


#collections
collections:
  stories:
    output: true
    permalink: /:title/

# Syntax
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  parse_block_html: true
highlighter: rouge

# Paginate
paginate: 5

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
