# Site
name: "GILog"
description: "Software Developer"
favicon: "assets/images/logo/favicon2.ico"
baseurl: ""
email: "seob31@gmail.com"
utterances:
  repo: "seob31/blog-reply"
  issue-term: "pathname"
  theme: "github-light"
# logo: 'assets/images/logo/gilog.png'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

topics:
  Spring:
    name: Spring
    img: assets/images/spring.png
    bio: "Hi"

  Cloud:
    name: Cloud
    img: assets/images/cloud.png
    bio: "Blogger"

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      # author: Gil
      # avatar: assets/images/avatar1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
