# Site
name: "GILog"
description: "Software Developer"
favicon: "assets/images/logo/favicon2.ico"
baseurl: ""
email: "seob31@gmail.com"
photo: assets/images/me/me.png
utterances:
  repo: "seob31/blog-reply"
  issue-term: "pathname"
  theme: "github-light"
# logo: 'assets/images/logo/gilog.png'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# blog topics
topics:
  architecture:
    name: Architecture
    img: assets/images/topic/architecture.png
    url: architecture
  backend:
    name: Back-end
    img: assets/images/topic/backend.png
    url: backend
  frontend:
    name: Front-end
    img: assets/images/topic/frontend.png
    url: frontend
  cloud:
    name: Cloud&Container
    img: assets/images/topic/cloud.png
    url: cloud
  devops:
    name: DevOps
    img: assets/images/topic/devOps.png
    url: devops
  db:
    name: DataBase
    img: assets/images/topic/db.png
    url: db
  os:
    name: OS
    img: assets/images/topic/os.png
    url: os
  others:
    name: Others
    img: assets/images/topic/others.png
    url: others

# Defaults
defaults:
  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

    # all stroy
  - scope:
      path: "_stories"
      type: stories
    values:
      layout: story

#collections
collections:
  stories:
    output: true
    permalink: /:title/

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
  ]
