# Site
name: "GILog"
description: "Back-end Developer"
favicon: "assets/images/logo/favicon.ico"
baseurl: ""
email: ""
photo: assets/images/me/me.jpg
utterances:
  repo: "seob31/blog-reply"
  issue-term: "pathname"
  theme: "github-light"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-sitemap
  # - jekyll-paginate

include: ["_pages"]
permalink: /:title/

# blog topics
topics:
  architecture:
    name: Architecture
    img: assets/images/topic/architecture.png
    url: architecture
  backend:
    name: Back-end
    img: assets/images/topic/backend.png
    url: backend
  frontend:
    name: Front-end
    img: assets/images/topic/frontend.png
    url: frontend
  devops:
    name: DevOps
    img: assets/images/topic/devOps.png
    url: devops
  ai:
    name: AI
    img: assets/images/topic/ai.png
    url: ai
  others:
    name: Others
    img: assets/images/topic/others.png
    url: others

# Paginate
# paginate: 5

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts/en"
      type: posts
    values:
      layout: post
      permalink: 'en/posts/:title'
      language: en
  - scope:
      path: "_posts/ko"
      type: posts
    values:
      layout: post
      permalink: 'posts/:title'
      language: ko

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

    # all project
  - scope:
      path: "_projects/ko"
      type: projects
    values:
      layout: project
      permalink: 'projects/:title'
      language: ko
  - scope:
      path: "_projects/en"
      type: projects
    values:
      layout: project
      permalink: 'en/projects/:title'
      language: en

    # My Zone
  - scope:
      path: "_myZone"
      type: myZone
    values:
      layout: myZonePost
      permalink: 'myZone/:title'


#collections
collections:
  projects:
    output: true
  posts:
    output: true
  myZone:
    output: true

# Syntax
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  hard_wrap: false
  parse_block_html: true
highlighter: rouge

robots: true

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude:
  [
    README.markdown,
    package.json,
    grunt.js,
    Gruntfile.js,
    Gruntfile.coffee,
    node_modules,
    Gemfile.lock,
  ]
